anyware_controller-war/src/java/ch/harenberg/anyware/web/boundary/TenantController.java
package ch.harenberg.anyware.web.boundary;

import ch.harenberg.anyware.entity.Tenant;
import ch.harenberg.anyware.remoteSystems.RestClientForAnyware;
import ch.harenberg.anyware.remoteSystems.RestClientForSFDC;
import ch.harenberg.anyware.web.boundary.util.JsfUtil;
import ch.harenberg.anyware.web.boundary.util.PaginationHelper;
import ch.harenberg.anyware.web.session.TenantFacade;
import java.io.IOException;

import java.io.Serializable;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.List;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.ejb.EJB;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;
import org.json.simple.parser.ParseException;

@Named("tenantController")
@SessionScoped
public class TenantController implements Serializable {

    private Tenant current;
    private DataModel items = null;
    @EJB
    private ch.harenberg.anyware.web.session.TenantFacade ejbFacade;
    private PaginationHelper pagination;
    private int selectedItemIndex;

    public TenantController() {
    }

    public Tenant getSelected() {
        if (current == null) {
            current = new Tenant();
            selectedItemIndex = -1;
        }
        return current;
    }

    private TenantFacade getFacade() {
        return ejbFacade;
    }
    
    public List<Tenant> getTenantsList(){
        return getFacade().findAll();
        
    }

    public String getContactedDate() {
        if (current.getTrialReminderDate() == null) {
            return ResourceBundle.getBundle("/Bundle").getString("btnRecontact_Label");
        } else {
            SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
            return formatter.format(current.getTrialReminderDate());
        }
    }
    
    public String getInviteSentDate() {
        if (current.getTrialReminderDate() == null) {
            return ResourceBundle.getBundle("/Bundle").getString("btnInviteSent_Label");
        } else {
            SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
            return formatter.format(current.getTrialReminderDate());
        }
    }

    public String updateContactedDate() {
        Calendar cal = Calendar.getInstance();
        current.setTrialReminderDate(cal.getTime());
        getFacade().edit(current);

            recreateModel();
        return "List";
    }
    
    public String updateInvitedDate() {
        Calendar cal = Calendar.getInstance();
        current.setInvitationMailSentDate(cal.getTime());
        getFacade().edit(current);

            recreateModel();
        return "List";
    }
    
    public String initializeTenant() {
        try {
            getFacade().edit(current);
            current.setSCSAdminMail(current.getBsk() + ".mds@swisscom.com");
            RestClientForAnyware anyc = new RestClientForAnyware();
            current = anyc.createTenant(current);
            anyc.applyLicence(current);
            anyc.acceptEulaForTenant(current);
            Integer tenantAdminId = anyc.createTenantSuperUser(current);
            Integer firstRoleId = anyc.getFirstTenantRole(current);
            anyc.assignCustomerAdminRoles(current, tenantAdminId, firstRoleId);
            if(current.getIsTrial()){
                Calendar cal = Calendar.getInstance();
                current.setTrialStartDate(cal.getTime());
                cal.add(Calendar.DAY_OF_MONTH, 30);
                current.setTrialEndDate(cal.getTime());
            }
            getFacade().edit(current);
            JsfUtil.addSuccessMessage("Tenant Created");
            recreateModel();
            return "List";
            
        } catch (IOException ex) {
            Logger.getLogger(TenantController.class.getName()).log(Level.SEVERE, null, ex);
            JsfUtil.addErrorMessage(ex,"Error, check");
            return "List";
        } catch (ParseException ex) {
            Logger.getLogger(TenantController.class.getName()).log(Level.SEVERE, null, ex);
            JsfUtil.addErrorMessage(ex, "Error, check");
            return "List";
        }
    }
    

    public String getLicense(){
        ch.harenberg.anyware.boundary.tenantController tc = new ch.harenberg.anyware.boundary.tenantController();
        tc.updateTenantLicences();
        return "List";
    }
    
    public String orderLicence() {
        try {
            RestClientForSFDC sfdc = new ch.harenberg.anyware.remoteSystems.RestClientForSFDC();
            if (current.getLicenceKey() == null) {
                //no existing license, first order
                current.setLicenceID(sfdc.createOperatorOrderForNewLicense(current));
                current.setLicenceKey("Pending");
                getFacade().edit(current);
                JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("LicenseOrderSuccess"));
            } else {
                //licence exists, updating old licence
                current.setLicenceID(sfdc.createOperatorOrderForUpdateLicense(current));
                current.setLicenceKey("Pending");
                getFacade().edit(current);
                JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("LicenseOrderSuccess"));
            }

            recreateModel();
            return "List";
        } catch (IOException ex) {
            Logger.getLogger(TenantController.class.getName()).log(Level.SEVERE, null, ex);
            JsfUtil.addErrorMessage(ex, ResourceBundle.getBundle("/Bundle").getString("LicenseOrderError"));
            return null;
        } catch (Exception ex) {
            Logger.getLogger(TenantController.class.getName()).log(Level.SEVERE, null, ex);
            JsfUtil.addErrorMessage(ex, ResourceBundle.getBundle("/Bundle").getString("LicenseOrderError"));
            return null;
        }

    }

    public String revokeLicense() {
        try {
            RestClientForSFDC sfdc = new ch.harenberg.anyware.remoteSystems.RestClientForSFDC();
            sfdc.revokeCustomerLicence(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("LicenseRevokeSuccess"));
            current.setLicenceKey("Revoked");
            getFacade().edit(current);

            recreateModel();
            return "List";
        } catch (IOException ex) {
            Logger.getLogger(TenantController.class.getName()).log(Level.SEVERE, null, ex);
            JsfUtil.addErrorMessage(ex, ResourceBundle.getBundle("/Bundle").getString("LicenseRevokeError"));
            return null;
        } catch (Exception ex) {
            Logger.getLogger(TenantController.class.getName()).log(Level.SEVERE, null, ex);
            JsfUtil.addErrorMessage(ex, ResourceBundle.getBundle("/Bundle").getString("LicenseRevokeError"));
            return null;
        }
    }

    public PaginationHelper getPagination() {
        if (pagination == null) {
            pagination = new PaginationHelper(10) {

                @Override
                public int getItemsCount() {
                    return getFacade().count();
                }

                @Override
                public DataModel createPageDataModel() {
                    return new ListDataModel(getFacade().findRange(new int[]{getPageFirstItem(), getPageFirstItem() + getPageSize()}));
                }
            };
        }
        return pagination;
    }

    public String prepareList() {
        recreateModel();
        return "List";
    }

    public String prepareView() {
        current = (Tenant) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "View";
    }

    public String prepareCreate() {
        current = new Tenant();
        selectedItemIndex = -1;
        return "Create";
    }

    public String create() {
        try {
            getFacade().create(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("TenantCreated"));
            return prepareCreate();
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String prepareEdit() {
        current = (Tenant) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "Edit";
    }

    public String update() {
        try {
            getFacade().edit(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("TenantUpdated"));
            recreateModel();
            return "List";
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String destroy() {
        current = (Tenant) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        if (current.getLicenceKey() == null) {
            performDestroy();
            recreatePagination();
            recreateModel();
            return "List";
        } else {
            JsfUtil.addErrorMessage(ResourceBundle.getBundle("/Bundle").getString("TenantCannotBeDeleted"));
            recreatePagination();
            recreateModel();

anyware_controller-war/web/tenant/Edit.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright (C) 2014 SSD-TCHHAFR1

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.EditTenantTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:form>
                <h:panelGrid columns="4">
                    <h:outputLabel value="#{bundle.EditTenantLabel_bsk}" for="bsk" />
                    <h:inputText id="bsk" value="#{tenantController.selected.bsk}" title="#{bundle.EditTenantTitle_bsk}" />
                    <h:outputLabel value="#{bundle.EditTenantLabel_customerName}" for="customerName" />
                    <h:inputText id="customerName" value="#{tenantController.selected.customerName}" title="#{bundle.EditTenantTitle_customerName}" />
                    <h:outputLabel value="#{bundle.EditTenantLabel_customerStreet}" for="customerStreet" />
                    <h:inputText id="customerStreet" value="#{tenantController.selected.customerStreet}" title="#{bundle.EditTenantTitle_customerStreet}" />
                    <h:outputLabel value="#{bundle.EditTenantLabel_customerState}" for="customerState" />
                    <h:inputText id="customerState" value="#{tenantController.selected.customerState}" title="#{bundle.EditTenantTitle_customerState}" />
                    <h:outputLabel value="#{bundle.EditTenantLabel_customerZIP}" for="customerZIP" />
                    <h:inputText id="customerZIP" value="#{tenantController.selected.customerZIP}" title="#{bundle.EditTenantTitle_customerZIP}" />
                    <h:outputLabel value="#{bundle.EditTenantLabel_customerCity}" for="customerCity" />
                    <h:inputText id="customerCity" value="#{tenantController.selected.customerCity}" title="#{bundle.EditTenantTitle_customerCity}" />
                    <h:outputLabel value="#{bundle.EditTenantLabel_customerCountry}" for="customerCountry" />
                    <h:inputText id="customerCountry" value="#{tenantController.selected.customerCountry}" title="#{bundle.EditTenantTitle_customerCountry}" />
                    <h:outputLabel value="#{bundle.EditTenantLabel_customerDomain}" for="customerDomain" />
                    <h:inputText id="customerDomain" value="#{tenantController.selected.customerDomain}" title="#{bundle.EditTenantTitle_customerDomain}" />
                    <h:outputLabel value="#{bundle.EditTenantLabel_adminFirstName}" for="adminFirstName" />
                    <h:inputText id="adminFirstName" value="#{tenantController.selected.adminFirstName}" title="#{bundle.EditTenantTitle_adminFirstName}" />
                    <h:outputLabel value="#{bundle.EditTenantLabel_adminLastName}" for="adminLastName" />
                    <h:inputText id="adminLastName" value="#{tenantController.selected.adminLastName}" title="#{bundle.EditTenantTitle_adminLastName}" />                   
                    <h:outputLabel value="#{bundle.EditTenantLabel_customerMail}" for="customerMail" />
                    <h:inputText id="customerMail" value="#{tenantController.selected.customerMail}" title="#{bundle.EditTenantTitle_customerMail}" />
                    <h:outputLabel value="#{bundle.CreateTenantLabel_adminPassword}" for="adminPassword"/>
                    <h:inputText id="adminPassword" value="#{tenantController.selected.adminPassword}"/>
                    <h:outputLabel value="#{bundle.CreateTenantLabel_SCSAdminPassword}" for="SCSAdminPassword"/>
                    <h:inputText id="SCSAdminPassword" value="#{tenantController.selected.SCSAdminPassword}"/>
                    <h:outputLabel value="#{bundle.EditTenantLabel_adminLang}" for="adminLang" />
                    <p:selectOneRadio id="adminLang" value="#{tenantController.selected.adminLang}">
                        <f:selectItem itemLabel="#{bundle.selectLanguageGer}" itemValue="de"/>
                        <f:selectItem itemLabel="#{bundle.selectLanguageFra}" itemValue="fr"/>
                        <f:selectItem itemLabel="#{bundle.selectLanguageEng}" itemValue="en" />
                        <f:selectItem itemLabel="#{bundle.selectLanguageIt}" itemValue="it" />
                    </p:selectOneRadio>

                    <h:outputLabel value="#{bundle.EditTenantLabel_isTrial}" for="isTrial" />
                    <p:selectBooleanCheckbox value="#{tenantController.selected.isTrial}" />
                    <h:outputLabel value="#{bundle.EditTenantLabel_AppsOption}" for="mianywareapps" />
                    <p:selectBooleanCheckbox value="#{tenantController.selected.mianywareapps}" />
                    <h:outputLabel value="#{bundle.EditTenantLabel_SecurityOption}" for="mianywaresecurity" />
                    <p:selectBooleanCheckbox value="#{tenantController.selected.mianywaresecurity}" />
                    <h:outputLabel value="#{bundle.EditTenantLabel_ContentOption}" for="mianywarecontent" />
                    <p:selectBooleanCheckbox value="#{tenantController.selected.mianywarecontent}" />
                    <h:outputLabel value="#{bundle.EditTenantLabel_CSKContact}" for="cskContact"/>
                    <h:inputText id="cskContact" value="#{tenantController.selected.cskContact}" title="#{bundle.EditTenantLabel_CSKContact}"/>
                    <h:outputLabel value="#{bundle.EditTenantLabel_SalesContact}" for="salesContact"/>
                    <h:inputText id="salesContact" value="#{tenantController.selected.salesContact}" title="#{bundle.EditTenantLabel_SalesContact}"/>
                    <h:outputLabel value="#{bundle.EditTenantLabel_RecontactDate}" for="trialReminderDate"/>
                    <h:commandButton action="#{tenantController.updateContactedDate()}" id="trialReminderDate" type="submit" value="#{tenantController.contactedDate}"/>
                    <h:outputLabel value="#{bundle.EditTenantLabel_InviteDate}" for="invitationMailSentDate"/>
                    <h:commandButton action="#{tenantController.updateInvitedDate()}" id="invitationMailSentDate" type="submit" value="#{tenantController.inviteSentDate}"/>
                </h:panelGrid>
                <h:panelGrid columns="4">
                    <h:commandButton type="submit" action="#{tenantController.update}" value="#{bundle.EditTenantSaveLink}"/>
                    <h:commandButton type="submit" action="#{tenantController.prepareList}" value="#{bundle.EditTenantShowAllLink}" immediate="true"/>
                    <h:commandButton type="submit" action="#{tenantController.orderLicence()}" value="#{bundle.EditTenantOrderLicence}"/>
                    <h:commandButton type="submit" action="#{tenantController.revokeLicense()}" value="#{bundle.EditTenantRevokeLicense}"/>
                </h:panelGrid>
                <h:panelGrid columns="4">
                    <h:outputText value="Manual Setup with pre-provided Key"/>
                    <h:outputText value="License Key"/>
                    <h:inputText id="licenseKey" value="#{tenantController.selected.licenceKey}" />
                    <h:commandButton type="submit" action="#{tenantController.initializeTenant()}" value="Fire"/>
                </h:panelGrid>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

anyware_controller-war/web/tenant/List.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright (C) 2014 SSD-TCHHAFR1

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core">


    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ListTenantTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:form styleClass="jsfcrud_list_form">
                <h:outputText escape="false" value="#{bundle.ListTenantEmpty}" rendered="#{tenantController.items.rowCount == 0}"/>
                <h:panelGroup rendered="#{tenantController.items.rowCount > 0}">
                    <h:outputText value="#{tenantController.pagination.pageFirstItem + 1}..#{tenantController.pagination.pageLastItem + 1}/#{tenantController.pagination.itemsCount}"/>&nbsp;
                    <h:commandLink action="#{tenantController.previous}" value="#{bundle.Previous} #{tenantController.pagination.pageSize}" rendered="#{tenantController.pagination.hasPreviousPage}"/>&nbsp;
                    <h:commandLink action="#{tenantController.next}" value="#{bundle.Next} #{tenantController.pagination.pageSize}" rendered="#{tenantController.pagination.hasNextPage}"/>&nbsp;
                    <h:dataTable value="#{tenantController.items}" var="item" border="0" cellpadding="2" cellspacing="0" rowClasses="jsfcrud_odd_row,jsfcrud_even_row" rules="all" style="border:solid 1px">
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTenantTitle_bsk}"/>
                            </f:facet>
                            <h:outputText value="#{item.bsk}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTenantTitle_customerName}"/>
                            </f:facet>
                            <h:outputText value="#{item.customerName}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTenantTitle_customerMail}"/>
                            </f:facet>
                            <h:outputText value="#{item.customerMail}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTenantTitle_licenceKey}"/>
                            </f:facet>
                            <h:outputText value="#{item.licenceKey}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTenantTitle_tenantId}"/>
                            </f:facet>
                            <h:outputText value="#{item.tenantId}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTenantTitle_tenantDmPartitionId}"/>
                            </f:facet>
                            <h:outputText value="#{item.tenantDmPartitionId}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTenantTitle_tenantCmPartitionId}"/>
                            </f:facet>
                            <h:outputText value="#{item.tenantCmPartitionId}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTenantTitle_adminLang}"/>
                            </f:facet>
                            <h:outputText value="#{item.adminLang}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTenantTitle_isTrial}"/>
                            </f:facet>
                            <h:outputText value="#{item.isTrial}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTenantTitle_trialStartDate}"/>
                            </f:facet>
                            <h:outputText value="#{item.trialStartDate}">
                                <f:convertDateTime pattern="yyyy-MM-dd" />
                            </h:outputText>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTenantTitle_trialEndDate}"/>
                            </f:facet>
                            <h:outputText value="#{item.trialEndDate}">
                                <f:convertDateTime pattern="yyyy-MM-dd" />
                            </h:outputText>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTenantTitle_CustomerReminderDate}"/>
                            </f:facet>
                            <h:outputText value="#{item.trialReminderDate}">
                                <f:convertDateTime pattern="yyyy-MM-dd" />
                            </h:outputText>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTenantTitle_InvitationSendtDate}"/>
                            </f:facet>
                            <h:outputText value="#{item.invitationMailSentDate}">
                                <f:convertDateTime pattern="yyyy-MM-dd" />
                            </h:outputText>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="&nbsp;"/>
                            </f:facet>
                            <h:commandLink action="#{tenantController.prepareView}" value="#{bundle.ListTenantViewLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{tenantController.prepareEdit}" value="#{bundle.ListTenantEditLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{tenantController.destroy}" value="#{bundle.ListTenantDestroyLink}"/>
                        </h:column>
                    </h:dataTable>
                </h:panelGroup>
                <br />
                <h:commandLink action="#{tenantController.prepareCreate}" value="#{bundle.ListTenantCreateLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.ListTenantIndexLink}"/>

                <p:dataTable id="tbl" var="item" value="#{tenantController.tenantsList}" rendered="false">
                    <p:column>
                        <f:facet name="header">  
                            <h:outputText value="BSK" />  
                        </f:facet> 
                        <h:outputText value="#{item.bsk}"/>
                    </p:column>
                    <p:column>
                        <f:facet name="header">  
                            <h:outputText value="Customer Name" />  
                        </f:facet> 
                        <h:outputText value="#{item.customerName}"/>
                    </p:column>
                    <p:column>
                        <f:facet name="header">  
                            <h:outputText value="Admin E-Mail" />  
                        </f:facet> 
                        <h:outputText value="#{item.customerMail}"/>
                    </p:column>
                    <p:column>
                        <f:facet name="header">  
                            <h:outputText value="AdminPass" />  
                        </f:facet> 
                        <h:outputText value="#{item.adminPassword}"/>
                    </p:column>
                    <p:column>
                        <f:facet name="header">  
                            <h:outputText value="LicenceKey" />  
                        </f:facet> 
                        <h:outputText value="#{item.licenceKey}"/>
                    </p:column>
                    <p:column>
                        <f:facet name="header">  
                            <h:outputText value="tenantId" />  
                        </f:facet> 
                        <h:outputText value="#{item.tenantId}"/>
                    </p:column>
                    <p:column>
                        <f:facet name="header">  
                            <h:outputText value="tenantDmPartitionId" />  
                        </f:facet> 
                        <h:outputText value="#{item.tenantDmPartitionId}"/>
                    </p:column>
                    <p:column headerText="tenantCmPartitionId">
                        <f:facet name="header">  
                            <h:outputText value="tenantCmPartitionId" />  
                        </f:facet> 
                        <h:outputText value="#{item.tenantCmPartitionId}"/>
                    </p:column>
                    <p:column>
                        <f:facet name="header">  
                            <h:outputText value="SCS Mail" />  
                        </f:facet> 
                        <h:outputText value="#{item.SCSAdminMail}"/>
                    </p:column>
                    <p:column>
                        <f:facet name="header">  
                            <h:outputText value="SCS Pass" />  
                        </f:facet> 
                        <h:outputText value="#{item.SCSAdminPassword}"/>
                    </p:column>
                    <p:column>                        
                        <f:facet name="header">  
                            <h:outputText value="Trial Start Date" />  
                        </f:facet> 
                        <h:outputText value="#{item.trialStartDate}"/>
                    </p:column>
                    <p:column> 
                        <f:facet name="header">  
                            <h:outputText value="Trial End Date" />  
                        </f:facet>  
                        <h:outputText value="#{item.trialEndDate}"/>
                    </p:column>
                    <p:column> 
                        <f:facet name="header">  
                            <h:outputText value="Active Users" />  
                        </f:facet>  
                        <h:outputText value="#{item.activeUsers}"/>
                    </p:column>
                    <p:column> 
                        <f:facet name="header">  
                            <h:outputText value="Device Count" />  
                        </f:facet>  
                        <h:outputText value="#{item.deviceCount}"/>
                    </p:column>
                    <p:column> 
                        <f:facet name="header">  
                            <h:outputText value="Device Count active" />  
                        </f:facet>  
                        <h:outputText value="#{item.deviceCountActive}"/>
                    </p:column>
                    <p:column> 
                        <f:facet name="header">  
                            <h:outputText value="Certificate uploaded" />  
                        </f:facet>  
                        <h:outputText value="#{item.mdmCertificateUploaded}"/>
                    </p:column>
                </p:dataTable>

                <br/>
                <h:commandLink value="export to excel">
                    <p:dataExporter type="xls" target="tbl" fileName="tenants" />
                </h:commandLink>
                <br/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>